apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "0.1"
        memory: "256Mi"
      requests:
        cpu: "0.05"
        memory: "128Mi"
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
