apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops
spec:    
  containers:
  - image: dockersamples/visualizer:stable
    name: giropops22
    ports:
    - containerPort: 5025
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
